// { metadata:
//    { dateModifiedUser: '2018-11-13T11:46:20.747Z',
//      serverDate: '2018-11-14T15:17:40.860Z',
//      defaults: {},
//      seasonId: '2018',
//      leagueId: '1483123',
//      dateModifiedLeague: '2018-11-14T14:55:13.963Z',
//      status: 'regular-season' },
//   teams:
//    [ { teamAbbrev: 'NSJI',
//        waiverRank: 9,
//        teamLocation: 'No Skill Just',
//        teamNickname: 'Intangibles',
//        owners: [Array],
//        logoUrl:
//         'http://g.espncdn.com/lm-static/logo-packs/ffl/SmackTalk-LeoEspinosa/u_mad_bro-09.svg',
//        division: [Object],
//        teamTransactions: [Object],
//        teamId: 1,
//        record: [Object],
//        divisionStanding: 3,
//        logoType: 'vector',
//        overallStanding: 5 },
//      { teamAbbrev: 'GIRS',
//        waiverRank: 6,
//        teamLocation: 'Prime',
//        teamNickname: 'Time',
//        owners: [Array],
//        logoUrl:
//         'https://s.yimg.com/ny/api/res/1.2/h3vNZEv__7jkBJX1sDMPKg--~A/YXBwaWQ9aGlnaGxhbmRlcjtzbT0xO3c9NzQ0O2g9NTM4/http://media.zenfs.com/en/homerun/feed_manager_auto_publish_494/2bb41582f13e68d70bbf2e2fecd79db6',
//        division: [Object],
//        teamTransactions: [Object],
//        teamId: 2,
//        record: [Object],
//        divisionStanding: 5,
//        logoType: 'customValid',
//        overallStanding: 9 },
//      { teamAbbrev: 'KEV',
//        waiverRank: 5,
//        teamLocation: 'Bush',
//        teamNickname: 'League',
//        owners: [Array],
//        logoUrl:
//         'https://balladeer.files.wordpress.com/2016/08/george-w-bush-mouth-open.jpg?w=251&h=300',
//        division: [Object],
//        teamTransactions: [Object],
//        teamId: 3,
//        record: [Object],
//        divisionStanding: 5,
//        logoType: 'customValid',
//        overallStanding: 10 },
//      { teamAbbrev: 'Juul',
//        waiverRank: 3,
//        teamLocation: 'The True King',
//        teamNickname: 'Juul Snow',
//        owners: [Array],
//        logoUrl:
//         'https://i.imgur.com/xc2oOj3_d.jpg?maxwidth=640&shape=thumb&fidelity=medium',
//        division: [Object],
//        teamTransactions: [Object],
//        teamId: 4,
//        record: [Object],
//        divisionStanding: 1,
//        logoType: 'customValid',
//        overallStanding: 1 },
//      { teamAbbrev: 'COX',
//        waiverRank: 7,
//        teamLocation: 'The Fighting',
//        teamNickname: 'Cox',
//        owners: [Array],
//        logoUrl:
//         'http://f645.z3portal.com/image.php?width=1600&height=1600&image=/f/archivio/foto/558840/WhatGrandmotherDoesn_tRecognizeOnTheIngredients_LabelHurts_9.jpg',
//        division: [Object],
//        teamTransactions: [Object],
//        teamId: 5,
//        record: [Object],
//        divisionStanding: 4,
//        logoType: 'customValid',
//        overallStanding: 8 },
//      { teamAbbrev: 'BROO',
//        waiverRank: 11,
//        teamLocation: 'Brooxie',
//        teamNickname: 'Badazz',
//        owners: [Array],
//        logoUrl:
//         'https://i.pinimg.com/236x/41/05/8d/41058d7b7ba781783d81f0e765e55aaf.jpg',
//        division: [Object],
//        teamTransactions: [Object],
//        teamId: 6,
//        record: [Object],
//        divisionStanding: 2,
//        logoType: 'customValid',
//        overallStanding: 3 },
//      { division: [Object],
//        teamAbbrev: 'G4P',
//        waiverRank: 8,
//        teamTransactions: [Object],
//        teamId: 7,
//        record: [Object],
//        teamLocation: 'Procnotmyprez',
//        teamNickname: 'House of Payne',
//        owners: [Array],
//        divisionStanding: 3,
//        overallStanding: 6 },
//      { division: [Object],
//        teamAbbrev: 'MCLE',
//        waiverRank: 4,
//        teamTransactions: [Object],
//        teamId: 8,
//        record: [Object],
//        teamLocation: 'Team',
//        teamNickname: 'McLendon',
//        owners: [Array],
//        divisionStanding: 6,
//        overallStanding: 11 },
//      { teamAbbrev: '#ONE',
//        waiverRank: 12,
//        teamLocation: 'League',
//        teamNickname: 'Champions',
//        owners: [Array],
//        logoUrl:
//         'http://g.espncdn.com/lm-static/logo-packs/ffl/AtTheStadium-RobbHarskamp/At_The_Stadium_05.svg',
//        division: [Object],
//        teamTransactions: [Object],
//        teamId: 9,
//        record: [Object],
//        divisionStanding: 1,
//        logoType: 'vector',
//        overallStanding: 2 },
//      { teamAbbrev: 'DAD',
//        waiverRank: 1,
//        teamLocation: 'Team',
//        teamNickname: 'DAD',
//        owners: [Array],
//        logoUrl:
//         'https://www.masterfile.com/image/en/6114-06589547/father-and-son-fishing',
//        division: [Object],
//        teamTransactions: [Object],
//        teamId: 10,
//        record: [Object],
//        divisionStanding: 6,
//        logoType: 'custom',
//        overallStanding: 12 },
//      { teamAbbrev: 'GARF',
//        waiverRank: 10,
//        teamLocation: 'Frat',
//        teamNickname: 'Stafford',
//        owners: [Array],
//        logoUrl:
//         'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNwdgrJg3RfiGDvdarWKMRLaE2e_rY321oZEu2A7MkdLKxshdkow',
//        division: [Object],
//        teamTransactions: [Object],
//        teamId: 11,
//        record: [Object],
//        divisionStanding: 2,
//        logoType: 'customValid',
//        overallStanding: 4 },
//      { division: [Object],
//        teamAbbrev: 'PATT',
//        waiverRank: 2,
//        teamTransactions: [Object],
//        teamId: 12,
//        record: [Object],
//        teamLocation: 'Team',
//        teamNickname: 'Patterson',
//        owners: [Array],
//        divisionStanding: 4,
//        overallStanding: 7 } ] }